### ISSUE TITLE
Agenda - DevOps Mutualization SIG Meeting - Thursday 21 January 2021

### ISSUE THREAD

**Issue by mcleo-d** [finos/devops-mutualization#12]
## Date
Thursday 21 January 2021 - 12pm EST / 5pm UK

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Approve [previous meeting minutes](https://github.com/finos/devops-mutualization/issues/8#issue-736048224)
- [x] Recap SIG objectives 
- [x] Update on use of Github Discussions 
   - [x] DevOps Mutualization [Participants Team Invites]( https://github.com/finos/metadata/issues/769)
   - [x] Private mailing list 
- [x] [FINOS Podcast](https://github.com/finos/devops-mutualization/issues/16)
- [x]  SDLC/Change Management policy approach at banks 
- [x] AOB, Q&A & Adjourn (5mins)

## Meeting Minutes

- Discussion on using implementation of private discussions in the SIG
  - Private team on GitHub is ready for use
  - However, GitHub Teams are not yet integrated with LXF metrics and it is desirable to have such discussions be part of the LFX metrics
  - Therefore, as email discussion lists are enabled for LXF metrics, a proposal was tabled to use an email discussion list until Teams are metrics-enabled
  - The proposal to use an email discussion list for now was approved by silent consent
- FINOS Podcast
  - Led by @natishalom
  - Discussion on inviting FINOS DevOps SIG members to podcast on industry trends
  - Focus on industry participants, less on vendors, to make it more interesting to audience
  - Recorded podcast, not a live broadcast, so opportunity to edit and correct as needed
- SDLC/Change Management policy approach at banks
  - Desire for industry collaboration on common challenges for developing standards and procedures (e.g. how to evolve Software Development Standards for DevOps)
  - Discussion on managing and evolving policies and procedures, led by Jon Stronell from Morgan Stanley
  - Question/discussion on to what extent such SDLC controls/policies can be repositioned to support control automation (versus manual review/approval type steps).
  - Suggestion by @mcleo-d to invite a member from https://github.com/finos/open-regtech-sig to join for a discussion on the regulatory perspective
  - Brief discussion on availability (or lack thereof) of "handbooks" on regulations and regulatory expectations, in support of standardizing best practices
  - Example question relative to standardizing: if code reviews are mandated by policy, and code was produced by pair programming, can code review be omitted?
  - @mcleo-d mentioned https://edmcouncil.org/page/cdmc as a potential resource, will reach out for their input

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=md62056638ba05fbea86b9582df94f807

### Dial-in
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 662 6070

**Github Repo:** https://github.com/finos/devops-mutualization/

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by ashukla13** [comment]
hello, i'm on

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by erictice** [comment]
hello

**Comment by leefaus** [comment]
hola! 🕺🏻

**Comment by pmanlukas** [comment]
Hello :)

**Comment by jccwm** [comment]
Hello 👋🏻

**Comment by peter-murray** [comment]
Hi 👋

**Comment by bdellegrazie** [comment]
Hello

**Comment by EarthmanT** [comment]
Hi :)

**Comment by awallgren** [comment]
Joining as soon as latest mandatory WebEx update completes...but hello!

**Comment by jbjonesjr** [comment]
👋  everyone! Happy 2021

**Comment by junjikatto** [comment]
Hi there!

**Comment by agitana** [comment]
Hello!

**Comment by guspaul** [comment]
Hello.

**Comment by edushak** [comment]
Hi
