### ISSUE TITLE
FINOS Podcast Outline 

### ISSUE THREAD

**Issue by natishalom** [finos/devops-mutualization#16]
As discussed previously please find bellow the outline of the Podcast outline that I wanted to suggest to introduce Finos to our local community (and potentially other communities as well)

I would welcome any suggestions, comments ...

**FINOS Podcast Outline** 
Target date: Jan 11, 9 AM EST

**Background**

The Cloud and Open Source effect on Fintech 
More collaboration between the industry and the financial sector
More openness
Quicker time to market with increased efficiency and quality
Potential to reduce cost as collaboration across the financial services industry increases  

Introduction to FINOS and DevOps Mutualization team
What is FINOS and what is the DevOps Mutualization Special Interest Group? Who’s collaborating in the group?

The transformation challenge  
The organization has invested decades in optimizing their current data center adding many layers of regulation, process, etc.
Transitioning all that to Cloud and Cloud Native is a long process.
In parallel new Fintech startups are disrupting the market and are forcing a faster transition..
What are the key challenges and what is the lesson learned for a successful transformation?

The need for collaboration to speed up the learning curve and avoid falling on other people’s mistakes 
There are many common challenges and best practices including lessons from the previous failure that can be shared in a community…

How can the FINOS DevOps Mutualization Special Interest Group help?
Develop common best practices and champion industry open-source projects 
Influence DevOps, Cloud, and other ecosystem vendors 
Networking, problem and ideas sharing

Who should consider joining and contributing with the Fintech Open Source Foundation, FINOS?

For more background see - [this google doc refernece](https://docs.google.com/document/d/1elTpy02SXvpPq2-pLapH5NWZRsbRIoSqto_yBqR0RF8/edit?usp=sharing )

**Comment by mcleo-d** [comment]
Hi @natishalom 

Thanks for submitting this GitHub issue and opening the opportunity to be interview by the Cloudify podcast. I suggest we ask the following people if they would like to be involved in the recording knowing how they are pursuing this space ...

- @ashukla13 - [DevOps Mutualization](https://github.com/finos/devops-mutualization) Lead from Morgan Stanley
- @peterrhysthomas - [Cloud Service Certification](https://github.com/finos/cloud-service-certification) Lead Maintainer from Deutsche Bank
- @grovesy - [DataHub](https://github.com/finos/datahub) and [GitProxy](https://github.com/finos/git-proxy) Lead Maintainer from Citi 
- @mcleo-d - FINOS Director of Community

It would be good to get the views of @ashukla13 and the DevOps Mutualiztion SIG on Thursday 21st January's call #12

James.

**Comment by mcleo-d** [comment]
This issue is now closed and has been delivered by @natishalom and the Cloudify team. Thank you!

>This session talks about FINOS (the Fin-tech Open Source foundation), a community creating open-source oriented solutions for financial services. This episode features special guests James McLeod, Director of Community at FINOS, and Amol Shukla, an Executive Director at Morgan Stanley talking all things FINOS, DevOps mutualization, banking and tech. 
https://cloudify.co/blog/podcast-episode-eleven-all-things-finos/
