### ISSUE TITLE
Agenda - DevOps Mutualization SIG Meeting - Thursday 18 February 2021

### ISSUE THREAD

**Issue by mcleo-d** [finos/devops-mutualization#18]
## Date
Thursday 18 February 2021 - 12pm EST / 5pm UK

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] [Approve previous meeting minutes](https://github.com/finos/devops-mutualization/issues/12)
- [x] Help Wanted 🙋  GitHub Discussions SIG rollout testing - @ashukla13 , @mcleo-d  
- [x] DevOps challenges and strategy discussion - Itau Unibanco
- [x] [GitProxy ](https://github.com/finos/git-proxy)as an example project to address DevOps challenges at banks - @grovesy 
- [x]  Feedback on IoT and EdgeX for Retail Banking [finos/community#98 ](https://github.com/finos/community/issues/98) - @dpbrookes
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ]

## Action Items
- [ ]

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=md62056638ba05fbea86b9582df94f807

### Dial-in
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 662 6070

**Github Repo:** https://github.com/finos/devops-mutualization/

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by dpbrookes** [comment]
Hi Guys, it would be great if I could get some feedback on IoT and EdgeX for Retail Banking https://github.com/finos/community/issues/98 from the call on Thursday. Thanks Dan

**Comment by mcleo-d** [comment]
> Hi Guys, it would be great if I could get some feedback on IoT and EdgeX for Retail Banking [finos/community#98](https://github.com/finos/community/issues/98) from the call on Thursday. Thanks Dan

Thanks @dpbrookes - I'm tagging @ashukla13 and @awallgren into this thread 👍

**Comment by ashukla13** [comment]
@dpbrookes are you able to join the call this Thursday to get feedback from the SIG? Happy to add this item to the agenda if that works.

**Comment by dpbrookes** [comment]
Yes plan to but will only be able to join for the last 30 mins

[cid:image002.png@01D7055A.E0292F70]

**Comment by ashukla13** [comment]
That'd be great - will add this to the later half of the agenda

**Comment by mcleo-d** [comment]
@ashukla13 and @grovesy,

Can we add the [Git Proxy](https://github.com/finos/git-proxy) update to the DevOps Mutualization agenda above as it would be great to highlight the approach as discussed with @ashukla13 and invite people to get involved in the project.

**Git Proxy**
https://github.com/finos/git-proxy

Many thanks,
James.

**Comment by tracymiranda** [comment]
Hello, looking forward to joining the all today, learn more & explore collaboration options with the cd.foundation

**Comment by ashukla13** [comment]
here

**Comment by mcleo-d** [comment]
Hello 👋 🐱

**Comment by adds68** [comment]
o/

**Comment by EarthmanT** [comment]
Hello!

**Comment by tcraigjohnson** [comment]
Howdy from California

**Comment by grovesy** [comment]
here

**Comment by eddie-knight** [comment]
:wave: :shipit:

**Comment by junjikatto** [comment]
Hello

**Comment by leefaus** [comment]
late, but here 👋🏻

**Comment by ashukla13** [comment]
hi
