### ISSUE TITLE
Agenda - DevOps Mutualization SIG Meeting - Thursday 18 March 2021

### ISSUE THREAD

**Issue by mcleo-d** [finos/devops-mutualization#19]
## Date
Thursday 18 March 2021 - 12pm EST / 4pm UK

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Approve previous meeting minutes 
- [x] [Regulation Innovation SIG](https://github.com/finos/open-regtech-sig) to join for a discussion on the regulatory perspective
   - [x] What regulators care about SDLC? 
   - [x] How does SDLC tie back to the regulatory landscape?
   - [x] What could the project look like?
   - [x] What format is easiest for regulators to consume?
   - [x] How do you approach the regulators?
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=md62056638ba05fbea86b9582df94f807

### Dial-in
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 662 6070

**Github Repo:** https://github.com/finos/devops-mutualization/

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by ashukla13** [comment]
hi, everyone

**Comment by EarthmanT** [comment]
Hi! - Trammell

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by eddie-knight** [comment]
:wave: :shipit:

**Comment by toshaellison** [comment]
Here!

**Comment by ThomasPerkins1123** [comment]
Hello

**Comment by bdellegrazie** [comment]
Hello!

**Comment by agitana** [comment]
hello!

**Comment by leefaus** [comment]
👋🏻  🕺🏻

**Comment by eduardosan** [comment]
Hello!

**Comment by jbjonesjr** [comment]
👋. i'm audio only/phone today, will catch slides later. i'm likely `call in user 2 `

**Comment by edushak** [comment]
Hi 👋

**Comment by fxHouard** [comment]
Hello 👋

**Comment by dehrich123** [comment]
Great to be here!

**Comment by tcraigjohnson** [comment]
Are there examples of 'drift' you can cite? For instance, a FINRA Trageted Examination letter has some specific details it asks about but how do those relate back to the regulations?

**Comment by guspaul** [comment]
Present

**Comment by mcleo-d** [comment]
> Hello 👋

Thanks for joining GitHub today @fxHouard 🥳 🎉  👏 💯

**Comment by mcleo-d** [comment]
Hi @ashukla13 - Is there an opportunity to contribute Jon Stronell's presentation on 18th March to DevOps Mutualization as markdown?

I'm more than happy to do the markdown conversion if that helps.

James.

**Comment by mcleo-d** [comment]
Hi DevOps Mutualization SIG,

The first DevOps Mutualization Team Discussion has been posted at https://github.com/orgs/finos/teams/devops-mutualization-participants/discussions/3 as highlighted below.

Please follow these instructions to [Join DevOps Mutualization Team Discussions](https://github.com/finos/devops-mutualization/blob/master/docs/Discussions.md). 

James.

![Screenshot 2021-04-06 at 14 53 47](https://user-images.githubusercontent.com/6029572/113722184-198a3880-96e8-11eb-9518-e8adf8664d55.png)
