### ISSUE TITLE
DevOps World 2021 Panel Discussion Preparation and Planning

### ISSUE THREAD

**Issue by tcraigjohnson** [finos/devops-mutualization#26]
See below for the CFP for DevOps World 2021.  Sessions will be recorded in August for broadcast in September.  This year we have a focus track on financial services so this is your opportunity to spread the word about successes, learnings, etc.  We have tracks for both Leadership and Practitioners.  We also have presentation training available if you need to sharpen your skills and I will also personally commit to helping you develop a compelling presentation.

Thanks in advance,
Tim Johnson
CloudBees
*******

We are now accepting proposals for DevOps World 2021 sessions and we would love to hear from you. Check out the [Call For Papers (CFP) Guide](https://assets.cloudbees.com/MzMzLVFQVi03MjUAAAF8UeHLpQ8SlQfHM1NgQ3GuGrWcL4ptRuK-VnQKxsSHdP2Rse0LFeUhz6FKK_adwJOAhkPOqfY=) and [submit your proposal](https://assets.cloudbees.com/MzMzLVFQVi03MjUAAAF8UeHLpcz4M4f8XbUd1R-ASwfWbr1NflncobFR4HlBINLSjWYOlE-uoEv9h8tJ2qLPaWhnh64=) by Thursday, May 20 for a chance to speak at this year’s event. 

We’re looking for speakers like yourself, who represent DevOps in action in the Financial Services sector to share: 

- Success stories around digital transformation - especially about GRC or audit - that give attendees the building blocks they need to take action
- Innovative and emerging open source projects that are shaping software delivery, examples of inclusive community building and guidance on being a good open source citizen
- Impactful conversations covering how tech organizations can cultivate a culture of inclusiveness and diversity
- Real-world examples of optimizing software delivery, while embracing existing tools as part of a DevOps journey

DevOps World is a free virtual conference taking place on September 28-30, 2021. Not interested in speaking but still want to attend DevOps World? Registration will be launching in June. Keep an eye out for more information.

**Comment by mcleo-d** [comment]
Hi @tcraigjohnson 👋 

Following a conversation with @ashukla13 and @awallgren, I have submitted the DevOps Mutualization CFP as a 30 minute panel discussion to include a selection of FINOS member banks. I have submitted using my speaker details, but expect to add others to this session as we discuss more with the SIG.

James 🚀

**Comment by ashukla13** [comment]
I'm happy to join the panel discussion as well.  @tcraigjohnson

**Comment by tcraigjohnson** [comment]
CFP is now closed.  Thanks to those who contributed.  Congrats to James and Amol for getting their panel selected.

**Comment by mcleo-d** [comment]
This issue has been reopened to help with the DevOps World panel discussion preparation.

**Comment by mcleo-d** [comment]
The FINOS DevOps Mutualization Special Interest Group solves common engineering problems by providing a continuous compliance and assurance approach to DevOps that mutually benefits banks, auditors and regulators whilst accelerating DevOps adoption in financial services engineering.

During this panel discussion of FINOS member banks the DevOps World audience will learn how DevOps Mutualization unites subject matter experts from across Engineering, IT, Compliance, Security and Audit to solve common financial services DevOps problems whilst sharing the outcome through FINOS.

**Comment by mcleo-d** [comment]
1. Key challenges/lesson learned for DevOps adoption at banks - by @ashukla13 
2. Specific examples/projects/topics that the DevOps SIG is working on - by @ashukla13
3. How you share these learnings outside your organization? - by @tcraigjohnson 
4. How can FINOS and DevOps SIG help banks and vendors? - by @ashukla13

**Comment by mcleo-d** [comment]
w/c 26th July planned recording date

**Comment by mcleo-d** [comment]
@ashukla13, @eduardosan, @peterrhysthomas , @peter-thomas-db and Ashok Singh,

Just letting you know that DevOps World will be contacting you for panelist information so they can add you to the event website. I am also working with the DevOps World team to confirm the recording session on **Tuesday 27th July at 6pm BST to 8pm BST**.

The questions being explored in the panel discussion are the following if you can get internal approval from comms teams etc ....

1. What is DevOps Mutualization and how does the special interest group enable engineering in banks?
2. What key challenges exist and what lessons can be learned around DevOps in banks?
3. How does your organisation safely share DevOps lessons learnt amongst your industry peers through FINOS?

I have also added to the SIG agenda here ... https://github.com/finos/devops-mutualization/issues/32

James 🚀

**Comment by eduardosan** [comment]
Just got their e-mail. Everything is fine from our side.

**Comment by mcleo-d** [comment]
Just letting you know that Tuesday's DevOps World panel discussion recording is being rescheduled by 1 week due to a few compliance check delays. 

Please keep an eye on this thread as I throw some date options forward to the group before committing to the next recording date.

Kind regards,

James 🚀
