### ISSUE TITLE
DevOps Mutualization : Automated Change Deployment Working Group - Thursday 29th July 2021

### ISSUE THREAD

**Issue by mcleo-d** [finos/devops-mutualization#33]
## Date
Thursday 29th July 2021 - 12pm EST / 5pm UK

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Approve [previous meeting minutes](https://github.com/finos/devops-mutualization/issues/28)
- [x] Private repo for the WG to collaborate has been setup - https://github.com/finos-labs/devops-mutualization-automated-change-deployment
- [x] WG members invited to join team - https://github.com/orgs/finos-labs/teams/devops-mutualization-automated-change-deployment
- [ ] Draft [Table of Contents/Outline of document](https://github.com/orgs/finos-labs/teams/devops-mutualization-automated-change-deployment/discussions/1) that describes what banks are doing to enable automated change deployment - only visible to Github Team for the WG
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
**Webex:** 
- **Meeting link:**  https://finos.webex.com/finos/j.php?MTID=mebf2cc13fcb7098b9eb3d85c017a4457
- **Meeting number:** 127 908 4269

### Dial-in
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 908 4269

**Github Repo:** https://github.com/finos/devops-mutualization/

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by mcleo-d** [comment]
_cc_

@TLATER @awallgren @RichardWagener365 @p-iyer @edushak @ashukla13 @guspaul

**Comment by ashukla13** [comment]
hi

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by RichardWagener365** [comment]
Hi

**Comment by TLATER** [comment]
Sorry, can't make it today!

**Comment by guspaul** [comment]
hi
