### ISSUE TITLE
Agenda - DevOps Mutualization SIG Meeting - Thursday 16 September 2021

### ISSUE THREAD

**Issue by mcleo-d** [finos/devops-mutualization#35]
## Date
Thursday 16 September 2021 - 12pm EST / 5pm UK

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Approve [previous meeting minutes](https://github.com/finos/devops-mutualization/issues/34)
- [x] DevOps SIG events at FINOS Member Meetings in London and New York // **_Promo code available for FINOS member registration_** - https://events.linuxfoundation.org/open-source-strategy-forum-london/register/
    - [x]  [London ](https://www.finos.org/hosted-events/2021-10-04-finos-members-meeting-2021-london) - **Monday 4th October from 12pm BST** - Automated Change Deployment Process, Tooling, and Regulatory Response // cc @guspaul 
    - [x]  [New York](https://www.finos.org/hosted-events/2021-11-09-finos-members-meeting-2021-new-york)  - **Tuesday 9th November** - DevOps Self Service tooling and other potential open source project ideas
- [x] Automated Change Deployment Working Group Update - https://github.com/finos-labs/devops-mutualization-automated-change-deployment
    - [x] Question : When should the WG next meet?
    - [x] Question : Who else should be recruited in order to help move forward?   
- [x] What other topics should DevOps SIG focus on in 2022? 
- [x] AOB, Q&A & Adjourn (5mins)
  - **Sept 28th to Sept 30th** : [DevOps World](https://t.sidekickopen07.com/s3t/c/5/f18dQhb0S7kF8bpVtZW1SXtrQ59hl3kW7_k2841CXdp3VNxQgy2Qy9y3W2dykgz8yBd3p101?te=W3R5hFj4cm2zwW4mKLS-3H4THBW45Vfsm49Nps2f3Fbt5S04&si=8000000001705677&pi=5e31aef6-d9ec-4c65-865e-fa1908dc87a0) - [FINOS DevOps Mutualization Special Interest Group Panel Discussion](https://t.sidekickopen07.com/s3t/c/5/f18dQhb0S7kF8bpVtZW1SXtrQ59hl3kW7_k2841CXdp3VNxQgy2Qy9y3W2dykgz8yBd3p101?te=W3R5hFj4cm2zwW4mKLS-3H4THBW45Vfsm49Nps2W3Fbt5S3zb1DHW3H34yy3K9dzfW43TwdF1N82dW2123&si=8000000001705677&pi=5e31aef6-d9ec-4c65-865e-fa1908dc87a0)
    - James McLeod, Director of Community at FINOS will lead this panel discussion with Amol Shukla from Morgan Stanley and Eduardo Ferreira Dos Santos from Itaú Unibanco. How DevOps mutualization unites subject matter experts from across Engineering, IT, Compliance, Security and Audit to solve common financial services DevOps problems.

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=md62056638ba05fbea86b9582df94f807

### Dial-in
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 662 6070

**Github Repo:** https://github.com/finos/devops-mutualization/

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by TLATER** [comment]
o/

**Comment by ashukla13** [comment]
here

**Comment by guspaul** [comment]
Hello

**Comment by pholleran** [comment]
![giphy (2)](https://user-images.githubusercontent.com/4007128/133646656-e1696b00-f6cb-41d4-a7d0-5b77017d140f.gif)

**Comment by jbjonesjr** [comment]
👋  🌊  Hi everyone!
