### ISSUE TITLE
DevOps Mutualization SIG Meeting - October 21, 2021

### ISSUE THREAD

**Issue by ashukla13** [finos/devops-mutualization#36]
## Date
21 OCT 2021  - 12pm ET / 5pm BST

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Approve [previous meeting minutes](https://github.com/finos/devops-mutualization/issues/35)
- [x]  DevOps SIG event at FINOS in-person Member Meeting in New York // Promo code available for FINOS member registration - https://www.finos.org/hosted-events/2021-11-09-finos-members-meeting-2021-new-york
   - [x]  Automated Change Deployment WG Discussion on processes, tooling, and regulatory response - chaired by Robb Keayes from Nomura - Nov 9 at 2:10 ET
- [x] OSSF London follow ups
   - [x]  Would Bank OSS programs find tooling that reports on lifecycle and decay of open source libraries (beyond security vulnerabilities) useful? 
- [x] 2022 Topics of Interest for the SIG
     - [x]  Managing End-of-Life Software Dependencies
     - [x]  SDLC policy as code 
     - [x] Other topics
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=md62056638ba05fbea86b9582df94f807

### Dial-in
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 662 6070

**Github Repo:** https://github.com/finos/devops-mutualization/

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by ashukla13** [comment]
here

**Comment by robbkeayes** [comment]
Hello, nice to be here
