### ISSUE TITLE
DevOps Mutualization SIG Meeting - November 18, 2021

### ISSUE THREAD

**Issue by ashukla13** [finos/devops-mutualization#37]
## Date
18 NOV 2021 - 12pm ET / 5pm BST

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Approve [previous meeting minutes](https://github.com/finos/devops-mutualization/issues/36)
- [x] Anders Wallgren resignation as DevOps Mutualization Secretary
- [x] Robb Keayes appointment as DevOps Mutualization Secretary - Discussion, nomination and second required
- [x] Robb Keayes (5-10m) summary of the FINOS NYC member meeting last week
- [x] Toby Weston (10-15m) discussion on SDLC policy as code 
- [x] @benjGenesis Question : https://github.com/finos/devops-mutualization/issues/37#issuecomment-970339272
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=md62056638ba05fbea86b9582df94f807

### Dial-in
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 662 6070

**Github Repo:** https://github.com/finos/devops-mutualization/

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by benjGenesis** [comment]
Hi all - quick intro - I'm Ben from Genesis Global (FINOS member). James M has pointed me to this SIG as I'm looking to tap into some community thinking about how firms, particularly vendors like Genesis, can work together on improving how we approach infosec and devops best practice etc. How are firms organising themselves to deal with this ever growing challenge? Can we learn things from each other? Additionally, it would be great as a community if we could work together to find better and more efficient ways to work together on how we address these challenges.

**Comment by RichardWagener365** [comment]
Richard - Codethink

**Comment by eduardosan** [comment]
Hello

**Comment by ashukla13** [comment]
Hello!

**Comment by rarkins** [comment]
Hi!

**Comment by benjGenesis** [comment]
I'm here - Ben Jefferys, Genesis Global

**Comment by tobyweston** [comment]
hello :smile:

**Comment by robbkeayes** [comment]
Hello everyone, Robb Keayes, Nomura

**Comment by ashukla13** [comment]
On behalf of the DevOps Mutualization SIG, I'd like to thank @awallgren for his contributions to the SIG in his secretary role over the past year. We look forward to continue working with him in the SIG in the future

**Comment by mcleo-d** [comment]
@robbkeayes **nominated** as SIG Secretary by @ashukla13 of Morgan Stanley and **seconded** by @tobyweston of Deutsche Bank.

@robbkeayes - Welcome to the role of DevOps Mutualization SIG Secretary 👏🏻
