### ISSUE TITLE
DevOps Mutualization SIG Meeting - Oct 20, 2022 

### ISSUE THREAD

**Issue by ashukla13** [finos/devops-mutualization#63]
## Date
October20  2022 - 12pm ET / 5pm BST

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [ ] Convene, roll call, welcome new people
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Approve [previous meeting minutes](#59)
- [ ] Review DevOps SIG [project board](https://github.com/orgs/finos/projects/33) 
- [ ] [Backstage](https://backstage.io/) Discussion - John Mark Walker, Director of Open Source Program Office, Fannie Mae
> https://groups.google.com/a/finos.org/g/community/c/FrasELXkQmw
> I’ve noticed that a lot of companies are implementing [backstage.io](https://backstage.io/) as part of an overall developer experience / dev scaffolding effort. It seems to be an emerging standard. I was wondering if there would be enough interest from other members to form a SIG on this subject? Or perhaps this falls under the purview of an existing SIG? Seems like there’s a lot we could learn from each other in financial services on this topic.

and ...

> Given that there are 2 SIGs ([InnerSource](https://github.com/finos/innersource) and [DevOps SIG](https://github.com/finos/devops-mutualization/)) where this is probably relevant, should we have a combined session, or do we think that each SIG will have its own points of emphasis and discussion points?
> I’m open to suggestions, but I would vote for 2 sessions: the devops mutualization forum can get into a technical discussion around automated compliance and the developer experience, as well as the tools and platforms that we can or should standardize on, and the innersource discussion can be about repeatable patterns and the intersections between developer experience and innersource programs. But if there are strong opinions that those are functionally discussions about the same thing, I’m happy to support a joint discussion.

- [ ] AOB, Q&A & Adjourn (5mins)

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=md62056638ba05fbea86b9582df94f807

### Dial-in
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 662 6070

**Github Repo:** https://github.com/finos/devops-mutualization/

**Project Board:** https://github.com/orgs/finos/projects/33

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by ashukla13** [comment]
hello!

**Comment by mcleo-d** [comment]
Hello - 👋🏻

**Comment by olcuhu** [comment]
Hi! :wave:

**Comment by RichardWagener365** [comment]
Hi

**Comment by serenamarie125** [comment]
👋🏼 hello!

**Comment by andrewduckett** [comment]
:wave: Hi!

**Comment by cronky** [comment]
Hello all. Oliver from Scott Logic here.

**Comment by claredillon** [comment]
Hello there! Clare from InnerSource Commons here.

**Comment by timjenkel** [comment]
Hi, this is Tim from Wellington Management

**Comment by mstelz** [comment]
Hey 👋

**Comment by robbkeayes** [comment]
Hi everyone
