### ISSUE TITLE
Agenda - DevOps Mutualization SIG Meeting - Monday November 16 2020

### ISSUE THREAD

**Issue by ashukla13** [finos/devops-mutualization#8]
### Date
**Monday November 16th 2020 - 11am ET / 4pm GMT**

### Untracked attendees
|Name | Firm | GitHub |
|----|----|----|
|James McLeod | FINOS | @mcleo-d |
| Amol Shukla | Morgan Stanley | @ashukla13 |
| Anders Wallgren | CloudBees | @awallgren |
 
### Agenda
- [x] Convene, roll call, welcome new people
- [x] What do you consider as the **Operating Model** for the DevOps SIG?
    - GitHub for communication (GitHub Issues, Project Boards, GitHub Teams, etc)?
    - Setup GitHub Team with DevOps SIG participants only to optionally allow [restricted SIG team discussions](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-team-discussions) 
- [x] What do you consider as the **success criteria** for the DevOps SIG?
    - Working off the 2 themes below ...
        - SDLC Evidence (https://github.com/finos-labs/devops-mutualization/issues/4)
        -  Self Service Orchestration "Glue" (https://github.com/finos-labs/devops-mutualization/issues/2)
            - For the next quarter
            - For the next 2 quarters
            - For the next year
- [x] Identify topics we can work on offline through in December
- [x] AOB, Q&A & Adjourn

### Meeting Minutes

- @mcleo-d to investigate GitHub Team Discussions for open and private team discussions - _linked to_ #1
  - [Devops Mutualization Maintainers](https://github.com/orgs/finos/teams/devops-mutualization-maintainers) team created with SIG leadership invited to join.
  - [Devops Mutualization Participants](https://github.com/orgs/finos/teams/devops-mutualization-participants) team created with SIG participants invited to join ongoing.
  - FINOS team investigating LF Analytics roadmap so SIG conversations and success is represented in open FINOS metrics.
- Special Interest Group to collaborate asynchronously during December whilst team members leave for winter breaks.
  - SIG to collaborate in the following open issues until #1 is resolved through GitHub Team Discussions
  - Structuring conversations around SDLC and Iterating the different types of evidence that needs to be produced #4
  - How are banks orchestrating DevOps and the 'Glue' utilised to create existing self-service workflows? #2
- SIG to input thoughts, outcomes and potential projects for 2021 Q1 agreement in #2 and #4  
- @ashukla13 and @awallgren to schedule and communicate January 2021 meeting

### Meeting Info

**Project Repository**
https://github.com/finos/devops-mutualization/

**WebEx Details**
https://finos.webex.com/meet/community

**US Toll**
+1-415-655-0003

**UK Toll**
+44-20319-88141

**Access ID**
668 959 028 #

**Comment by ashukla13** [comment]
@mcleo-d @anderswallgren - please review

**Comment by cr20ro20** [comment]
Hello from Craig Rowe

**Comment by aitana16** [comment]
Good morning!

**Comment by awallgren** [comment]
Hello everyone!

**Comment by peterrhysthomas** [comment]
hi

**Comment by brooklynrob** [comment]
here.

**Comment by jonbodner** [comment]
here

**Comment by jbjonesjr** [comment]
👋 Good morning, afternoon, or evening everyone (depending on how timezones work)

**Comment by bdellegrazie** [comment]
here

**Comment by mcleo-d** [comment]
Thank you all. Please keep saying hello :)

**Comment by tcraigjohnson** [comment]
Good morning

**Comment by edushak** [comment]
Hi

**Comment by ashukla13** [comment]
Hi, everyone

**Comment by mekhla18** [comment]
Hello

**Comment by DovOps** [comment]
here

**Comment by adamj-codethink** [comment]
Hey o/

**Comment by erictice** [comment]
Hello

**Comment by RichardWagener365** [comment]
Hi
